from .core_decoders import identify_core_in_ds, core_dicts_from_ds
from .ds_decoders import map_ds_to_gp, find_addable_vars_and_magnitudes
from .setters import set_core_vars_to_skeleton_from_ds, add_dynamic_vars_from_ds
from .coord_remapping import remap_coords_of_ds_vars_to_skeleton_names
